content_parser.c: convert to rcur.
1. rcur_peek returns a pointer, clearer than cursor's peek_char.
2. parse functions which leave untouched on failure renamed to "parse_if_xxx".
3. consume_until_end_url "or_end" is always true, remove it.
4. Don't look backwards for '(' before URL, pass in from caller.

I had to change parse_if_mention_index, since GCC didn't understand
d3 couldn't be a digit unless d2 was:

```
In function ‘parse_if_mention_index’,
    inlined from ‘ndb_parse_content’ at src/content_parser.c:518:8:
src/content_parser.c:57:40: error: ‘d2’ may be used uninitialized [-Werror=maybe-uninitialized]
   57 |                 ind = (d1 * 100) + (d2 * 10) + d3;
      |                                    ~~~~^~~~~
src/content_parser.c: In function ‘ndb_parse_content’:
src/content_parser.c:42:17: note: ‘d2’ was declared here
   42 |         int d1, d2, d3, ind;
      |                 ^~
cc1: all warnings being treated as errors
```

Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>